
language: python
python:
  - "3.8.3"

install:
  - pip install codecov

stages:
  - name: test

jobs:
  include:
  - stage: test
    name: Unit Test
    script: python manage.py test
    after_success:
      - codecov
